main: me.flail.ChatSwap.ChatSwap
name: ChatSwap
author: FlailoftheLord
version: 1.1
api-version: 1.13
description: replace unwanted chat with something more healthy :>

commands:
  chatswap:
    description: main command
    aliases: [cs, cswap]
    
permissions:
  chatswap.command:
    description: use the main command
    default: op