main: me.flail.ChatSwap.ChatSwap
name: ChatSwap
author: FlailoftheLord
version: 1.2
api-version: 1.13
description: replace unwanted chat with something more healthy :>
softdepend: [Vault]

commands:
  chatswap:
    description: main command
    aliases: [cs, cswap]
    
permissions:
  chatswap.command:
    description: use the main command
    default: op