#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#                 Plugin by FlailoftheLord.                        #
#        -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                   #
#        For questions please join my discord server:              #
#                https://discord.gg/wuxW5PS                        #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------

# The way this works is, you add a phrase or word or list of phrases and words
# which, when said in chat by a player, will be replaced with a pre-defined
# word or phrase from a list either randomly, or the same one every time if you only add one word.
# its explained in more detail below :>

# Prefix for messages, such as reloading and modifications
# use the  %prefix%  placeholder.
Prefix: "&6&lCS&8:"

ReloadMessage: "%prefix% &aplugin files reloaded!"

# Wether to pick a random response/replacement when there are multiple options in the list.
# setting to false will pick the corosponding message, or use the first one if there aren't enough to go around.
RandomReplacements: true

# This entire configuration below is all modular, simply add a new section with whatever name you like!
# then add the sections:
#  messages, responses/replacements... ect.
# if you'r enot sure follow the template below
#
# Valid types are 'replace' , 'respond' , and 'swap'
# replace will replace that word/phrase in the chat message sent.
# swap will swap the entire message with the response.
# respond will send a message back to the player.

ChatSwap:

  ExampleOne:
    type: replace
    ignore-punctuation: true
    ignore-spaces: true
    ignore-case: true
    messages:
    - "suck"
    - "u suck"
    - "you suck"
    replacements:
    - "hiya!"
  
  SectionTwo:
    type: swap
    ignore-punctuation: false
    ignore-spaces: true
    ignore-case: true
    messages:
    - "fuck"
    - "nigger"
    - "kys"
    - "kill yourself"
    replacements:
    - "sorry"
    - "oh, my bad!"
    - "<3"

